<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mir</string>
		<string>MIR</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~L</string>
	<key>name</key>
	<string>MIR</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>mir instructions</string>
			<key>match</key>
			<string>(?x)\b(
				[ ]x[ ] |
				add |
				alloca |
				and |
				ashr |
				atomic |
				atomicrmw |
				bitcast |
				br |
				call |
				cleanup |
				cmpxchg |
				contract |
				dso_local |
				eq |
				exact |
				extractelement |
				extractvalue |
				fadd |
				fast |
				fcmp |
				fdiv |
				fence |
				fmul |
				fneg |
				fpext |
				fptosi |
				fptoui |
				fptrunc |
				frem |
				fsub |
				getelementptr |
				icmp |
				inbounds |
				indirectbr |
				insertelement |
				insertvalue |
				inttoptr |
				invoke |
				landingpad |
				load |
				lshr |
				mul |
				ne |
				nnan |
				nneg |
				noundef |
				nsw |
				nsz |
				nuw |
				oeq |
				oge |
				ogt |
				ole |
				olt |
				one |
				or |
				ord |
				phi |
				poison |
				ptrtoint |
				resume |
				ret |
				sdiv |
				select |
				sext |
				sge |
				sgt |
				shl |
				shufflevector |
				sitofp |
				sle |
				slt |
				srem |
				store |
				strictfp |
				sub |
				switch |
				to |
				trunc |
				udiv |
				ueq |
				uge |
				uge |
				ugt |
				ugt |
				uitofp |
				ule |
				ule |
				ult |
				ult |
				une |
				uno |
				unreachable |
				unwind |
				urem |
				va_arg |
				vscale |
				xor |
				zext
				)\b(?!\s*:)</string>
			<key>name</key>
			<string>keyword.instruction.mir</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>mir keywords</string>
			<key>match</key>
			<string>(?ix)\b(
				acq_rel |
				acquire |
				addrspace |
				alias |
				align |
				alignstack |
				alwaysinline |
				appending |
				argmemonly |
				asm |
				attributes |
				blockaddress |
				byval |
				c |
				cc |
				ccc |
				coldcc |
				common |
				constant |
				convergent |
				datalayout |
				declare |
				default |
				define |
				deplibs |
				dereferenceable |
				dereferenceable_or_null |
				distinct |
				dllexport |
				dllimport |
				except |
				extern_weak |
				external |
				false |
				fastcc |
				gc |
				global |
				hidden |
				immarg |
				inaccessiblemem_or_argmemonly |
				inaccessiblememonly |
				inalloca |
				inlinehint |
				inreg |
				internal |
				jumptable |
				linkonce |
				linkonce_odr |
				local_unnamed_addr |
				memory |
				metadata |
				minsize |
				module |
				monotonic |
				naked |
				nest |
				noalias |
				nobuiltin |
				nocallback |
				nocapture |
				noduplicate |
				nofree |
				noimplicitfloat |
				noinline |
				nonlazybind |
				nonnull |
				norecurse |
				noredzone |
				noreturn |
				nosync |
				nounwind |
				null |
				opaque |
				optnone |
				optsize |
				personality |
				prefix |
				private |
				prologue |
				protected |
				ptx_device |
				ptx_kernel |
				readnone |
				readonly |
				readwrite |
				release |
				returned |
				returns_twice |
				safestack |
				sanitize_address |
				sanitize_memory |
				sanitize_thread |
				section |
				seq_cst |
				sideeffect |
				signext |
				source_filename |
				sret |
				ssp |
				sspreq |
				sspstrong |
				swifterror |
				swiftself |
				tail |
				target |
				thread_local |
				triple |
				true |
				type |
				undef |
				unnamed_addr |
				unordered |
				uwtable |
				volatile |
				weak |
				weak_odr |
				willreturn |
				writeonly |
				x86_fastcallcc |
				x86_stdcallcc |
				zeroext |
				zeroinitializer
				)\b(?!\s*:)</string>
			<key>name</key>
			<string>storage.modifier.mir</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([%@\$][-a-zA-Z$._][-a-zA-Z$._0-9]*(\s*\*)+)</string>
			<key>name</key>
			<string>storage.type.mir</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?x)\b(
				bfloat |
				double |
				float |
				fp128 |
				half |
				i\d+\** |
				metadata |
				ppc_fp128 |
				ptr |
				void |
				x86_fp80 |
				x86mmx
				)</string>
			<key>name</key>
			<string>storage.type.language.mir</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([%@\$][-a-zA-Z$._][-a-zA-Z$._0-9]*)</string>
			<key>name</key>
			<string>variable.language.mir</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([%]\d+)</string>
			<key>name</key>
			<string>variable.language.mir</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(#\d+)</string>
			<key>name</key>
			<string>variable.metadata.mir</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(!\d+)</string>
			<key>name</key>
			<string>variable.metadata.mir</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(![-a-zA-Z$._][-a-zA-Z$._0-9]*)</string>
			<key>name</key>
			<string>variable.metadata.mir</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.label.mir</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([.A-Za-z0-9_]+):</string>
			<key>name</key>
			<string>meta.function.label.ir</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.label.mir.2</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\blabel( %[.A-Za-z0-9_]+)\b</string>
			<key>name</key>
			<string>meta.function.label.ir.2</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[;#].*$</string>
			<key>name</key>
			<string>comment.mir</string>
		</dict>
		<dict>
			<key>match</key>
        <string>(?ix)\b(
          \d+\.\d+ |
          \d+\.\d+[e][+-]\d+ |
          \d+|0(x|X)[a-fA-F0-9]+(\.[a-fA-F0-9]*)?c?p[+-]\d+
          )\b</string>
			<key>name</key>
			<string>constant.numeric.float.mir</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(\d+|0(x|X)[a-fA-F0-9]+)\b</string>
			<key>name</key>
			<string>constant.numeric.integer.mir</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.mir</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\..</string>
					<key>name</key>
					<string>constant.character.escape.mir</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.mir</string>
	<key>uuid</key>
	<string>BA22CCD7-4BFB-434E-9D80-79FB1758A944</string>
</dict>
</plist>
